### ISSUE TITLE
to_stream returns NoMethodError from rubyzip 1.2.0

### ISSUE THREAD

**Issue by wdiechmann** [randym/axlsx#461]
when I hit localhost:3000/stock_items.xlsx, this is what my output looks like:

   NoMethodError - undefined method 'reopen' for "streamed":String:

```
   rubyzip (1.2.0) lib/zip/output_stream.rb:32:in 'initialize'
   axlsx (1.3.6) lib/axlsx/package.rb:113:in 'to_stream'
   app/views/stock_items/index.xlsx.axlsx:16:in '_app_views_stock_items_index_xlsx_axlsx___3308310048101462186_70144462088640'
```

my index.xlsx.axlsx looks like this:

```
wb = xlsx_package.workbook
wb.styles do |style|
  highlight_cell = style.add_style(bg_color: "EFC376")

  wb.add_worksheet(name: "Wheels") do |sheet|
    resources.each do |resource|
      sheet.add_row [
        1000,2000
      ],
      style: [nil, highlight_cell]
    end
  end
end
```

**Comment by orangethunder** [comment]
lib/axlsx/package.rb has a fix for this on master. Just applied it to my very out of date fork.

**Comment by randym** [comment]
3.0.0pre
